
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Lease` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Lease
 * 
 */
export type LeaseModel = runtime.Types.Result.DefaultSelection<Prisma.$LeasePayload>

export type AggregateLease = {
  _count: LeaseCountAggregateOutputType | null
  _avg: LeaseAvgAggregateOutputType | null
  _sum: LeaseSumAggregateOutputType | null
  _min: LeaseMinAggregateOutputType | null
  _max: LeaseMaxAggregateOutputType | null
}

export type LeaseAvgAggregateOutputType = {
  id: number | null
  rent: number | null
  deposit: number | null
  propertyId: number | null
}

export type LeaseSumAggregateOutputType = {
  id: number | null
  rent: number | null
  deposit: number | null
  propertyId: number | null
}

export type LeaseMinAggregateOutputType = {
  id: number | null
  startDate: Date | null
  endDate: Date | null
  rent: number | null
  deposit: number | null
  propertyId: number | null
  tenantCognitoId: string | null
}

export type LeaseMaxAggregateOutputType = {
  id: number | null
  startDate: Date | null
  endDate: Date | null
  rent: number | null
  deposit: number | null
  propertyId: number | null
  tenantCognitoId: string | null
}

export type LeaseCountAggregateOutputType = {
  id: number
  startDate: number
  endDate: number
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: number
  _all: number
}


export type LeaseAvgAggregateInputType = {
  id?: true
  rent?: true
  deposit?: true
  propertyId?: true
}

export type LeaseSumAggregateInputType = {
  id?: true
  rent?: true
  deposit?: true
  propertyId?: true
}

export type LeaseMinAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  rent?: true
  deposit?: true
  propertyId?: true
  tenantCognitoId?: true
}

export type LeaseMaxAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  rent?: true
  deposit?: true
  propertyId?: true
  tenantCognitoId?: true
}

export type LeaseCountAggregateInputType = {
  id?: true
  startDate?: true
  endDate?: true
  rent?: true
  deposit?: true
  propertyId?: true
  tenantCognitoId?: true
  _all?: true
}

export type LeaseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Lease to aggregate.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Leases
  **/
  _count?: true | LeaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LeaseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LeaseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeaseMaxAggregateInputType
}

export type GetLeaseAggregateType<T extends LeaseAggregateArgs> = {
      [P in keyof T & keyof AggregateLease]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLease[P]>
    : Prisma.GetScalarType<T[P], AggregateLease[P]>
}




export type LeaseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaseWhereInput
  orderBy?: Prisma.LeaseOrderByWithAggregationInput | Prisma.LeaseOrderByWithAggregationInput[]
  by: Prisma.LeaseScalarFieldEnum[] | Prisma.LeaseScalarFieldEnum
  having?: Prisma.LeaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeaseCountAggregateInputType | true
  _avg?: LeaseAvgAggregateInputType
  _sum?: LeaseSumAggregateInputType
  _min?: LeaseMinAggregateInputType
  _max?: LeaseMaxAggregateInputType
}

export type LeaseGroupByOutputType = {
  id: number
  startDate: Date
  endDate: Date
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: string
  _count: LeaseCountAggregateOutputType | null
  _avg: LeaseAvgAggregateOutputType | null
  _sum: LeaseSumAggregateOutputType | null
  _min: LeaseMinAggregateOutputType | null
  _max: LeaseMaxAggregateOutputType | null
}

type GetLeaseGroupByPayload<T extends LeaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeaseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeaseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeaseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeaseGroupByOutputType[P]>
      }
    >
  >



export type LeaseWhereInput = {
  AND?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  OR?: Prisma.LeaseWhereInput[]
  NOT?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  id?: Prisma.IntFilter<"Lease"> | number
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  rent?: Prisma.FloatFilter<"Lease"> | number
  deposit?: Prisma.FloatFilter<"Lease"> | number
  propertyId?: Prisma.IntFilter<"Lease"> | number
  tenantCognitoId?: Prisma.StringFilter<"Lease"> | string
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  application?: Prisma.XOR<Prisma.ApplicationNullableScalarRelationFilter, Prisma.ApplicationWhereInput> | null
  payments?: Prisma.PaymentListRelationFilter
}

export type LeaseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenantCognitoId?: Prisma.SortOrder
  property?: Prisma.PropertyOrderByWithRelationInput
  tenant?: Prisma.TenantOrderByWithRelationInput
  application?: Prisma.ApplicationOrderByWithRelationInput
  payments?: Prisma.PaymentOrderByRelationAggregateInput
}

export type LeaseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  OR?: Prisma.LeaseWhereInput[]
  NOT?: Prisma.LeaseWhereInput | Prisma.LeaseWhereInput[]
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  rent?: Prisma.FloatFilter<"Lease"> | number
  deposit?: Prisma.FloatFilter<"Lease"> | number
  propertyId?: Prisma.IntFilter<"Lease"> | number
  tenantCognitoId?: Prisma.StringFilter<"Lease"> | string
  property?: Prisma.XOR<Prisma.PropertyScalarRelationFilter, Prisma.PropertyWhereInput>
  tenant?: Prisma.XOR<Prisma.TenantScalarRelationFilter, Prisma.TenantWhereInput>
  application?: Prisma.XOR<Prisma.ApplicationNullableScalarRelationFilter, Prisma.ApplicationWhereInput> | null
  payments?: Prisma.PaymentListRelationFilter
}, "id">

export type LeaseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenantCognitoId?: Prisma.SortOrder
  _count?: Prisma.LeaseCountOrderByAggregateInput
  _avg?: Prisma.LeaseAvgOrderByAggregateInput
  _max?: Prisma.LeaseMaxOrderByAggregateInput
  _min?: Prisma.LeaseMinOrderByAggregateInput
  _sum?: Prisma.LeaseSumOrderByAggregateInput
}

export type LeaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeaseScalarWhereWithAggregatesInput | Prisma.LeaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeaseScalarWhereWithAggregatesInput | Prisma.LeaseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Lease"> | number
  startDate?: Prisma.DateTimeWithAggregatesFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"Lease"> | Date | string
  rent?: Prisma.FloatWithAggregatesFilter<"Lease"> | number
  deposit?: Prisma.FloatWithAggregatesFilter<"Lease"> | number
  propertyId?: Prisma.IntWithAggregatesFilter<"Lease"> | number
  tenantCognitoId?: Prisma.StringWithAggregatesFilter<"Lease"> | string
}

export type LeaseCreateInput = {
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  tenant: Prisma.TenantCreateNestedOneWithoutLeasesInput
  application?: Prisma.ApplicationCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: string
  application?: Prisma.ApplicationUncheckedCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseUpdateInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  tenant?: Prisma.TenantUpdateOneRequiredWithoutLeasesNestedInput
  application?: Prisma.ApplicationUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  application?: Prisma.ApplicationUncheckedUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateManyInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: string
}

export type LeaseUpdateManyMutationInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type LeaseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LeaseListRelationFilter = {
  every?: Prisma.LeaseWhereInput
  some?: Prisma.LeaseWhereInput
  none?: Prisma.LeaseWhereInput
}

export type LeaseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeaseNullableScalarRelationFilter = {
  is?: Prisma.LeaseWhereInput | null
  isNot?: Prisma.LeaseWhereInput | null
}

export type LeaseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenantCognitoId?: Prisma.SortOrder
}

export type LeaseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type LeaseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenantCognitoId?: Prisma.SortOrder
}

export type LeaseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
  tenantCognitoId?: Prisma.SortOrder
}

export type LeaseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rent?: Prisma.SortOrder
  deposit?: Prisma.SortOrder
  propertyId?: Prisma.SortOrder
}

export type LeaseScalarRelationFilter = {
  is?: Prisma.LeaseWhereInput
  isNot?: Prisma.LeaseWhereInput
}

export type LeaseCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUncheckedCreateNestedManyWithoutPropertyInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput | Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseUncheckedUpdateManyWithoutPropertyNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput> | Prisma.LeaseCreateWithoutPropertyInput[] | Prisma.LeaseUncheckedCreateWithoutPropertyInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPropertyInput | Prisma.LeaseCreateOrConnectWithoutPropertyInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpsertWithWhereUniqueWithoutPropertyInput[]
  createMany?: Prisma.LeaseCreateManyPropertyInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput | Prisma.LeaseUpdateWithWhereUniqueWithoutPropertyInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput | Prisma.LeaseUpdateManyWithWhereWithoutPropertyInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUncheckedCreateNestedManyWithoutTenantInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
}

export type LeaseUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutTenantInput | Prisma.LeaseUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseUncheckedUpdateManyWithoutTenantNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput> | Prisma.LeaseCreateWithoutTenantInput[] | Prisma.LeaseUncheckedCreateWithoutTenantInput[]
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutTenantInput | Prisma.LeaseCreateOrConnectWithoutTenantInput[]
  upsert?: Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpsertWithWhereUniqueWithoutTenantInput[]
  createMany?: Prisma.LeaseCreateManyTenantInputEnvelope
  set?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  disconnect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  delete?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  connect?: Prisma.LeaseWhereUniqueInput | Prisma.LeaseWhereUniqueInput[]
  update?: Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput | Prisma.LeaseUpdateWithWhereUniqueWithoutTenantInput[]
  updateMany?: Prisma.LeaseUpdateManyWithWhereWithoutTenantInput | Prisma.LeaseUpdateManyWithWhereWithoutTenantInput[]
  deleteMany?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
}

export type LeaseCreateNestedOneWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutApplicationInput, Prisma.LeaseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutApplicationInput
  connect?: Prisma.LeaseWhereUniqueInput
}

export type LeaseUpdateOneWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutApplicationInput, Prisma.LeaseUncheckedCreateWithoutApplicationInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutApplicationInput
  upsert?: Prisma.LeaseUpsertWithoutApplicationInput
  disconnect?: Prisma.LeaseWhereInput | boolean
  delete?: Prisma.LeaseWhereInput | boolean
  connect?: Prisma.LeaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseUpdateToOneWithWhereWithoutApplicationInput, Prisma.LeaseUpdateWithoutApplicationInput>, Prisma.LeaseUncheckedUpdateWithoutApplicationInput>
}

export type LeaseCreateNestedOneWithoutPaymentsInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPaymentsInput
  connect?: Prisma.LeaseWhereUniqueInput
}

export type LeaseUpdateOneRequiredWithoutPaymentsNestedInput = {
  create?: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  connectOrCreate?: Prisma.LeaseCreateOrConnectWithoutPaymentsInput
  upsert?: Prisma.LeaseUpsertWithoutPaymentsInput
  connect?: Prisma.LeaseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.LeaseUpdateToOneWithWhereWithoutPaymentsInput, Prisma.LeaseUpdateWithoutPaymentsInput>, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
}

export type LeaseCreateWithoutPropertyInput = {
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  tenant: Prisma.TenantCreateNestedOneWithoutLeasesInput
  application?: Prisma.ApplicationCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutPropertyInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  tenantCognitoId: string
  application?: Prisma.ApplicationUncheckedCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput>
}

export type LeaseCreateManyPropertyInputEnvelope = {
  data: Prisma.LeaseCreateManyPropertyInput | Prisma.LeaseCreateManyPropertyInput[]
  skipDuplicates?: boolean
}

export type LeaseUpsertWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutPropertyInput, Prisma.LeaseUncheckedUpdateWithoutPropertyInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPropertyInput, Prisma.LeaseUncheckedCreateWithoutPropertyInput>
}

export type LeaseUpdateWithWhereUniqueWithoutPropertyInput = {
  where: Prisma.LeaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutPropertyInput, Prisma.LeaseUncheckedUpdateWithoutPropertyInput>
}

export type LeaseUpdateManyWithWhereWithoutPropertyInput = {
  where: Prisma.LeaseScalarWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyWithoutPropertyInput>
}

export type LeaseScalarWhereInput = {
  AND?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
  OR?: Prisma.LeaseScalarWhereInput[]
  NOT?: Prisma.LeaseScalarWhereInput | Prisma.LeaseScalarWhereInput[]
  id?: Prisma.IntFilter<"Lease"> | number
  startDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  endDate?: Prisma.DateTimeFilter<"Lease"> | Date | string
  rent?: Prisma.FloatFilter<"Lease"> | number
  deposit?: Prisma.FloatFilter<"Lease"> | number
  propertyId?: Prisma.IntFilter<"Lease"> | number
  tenantCognitoId?: Prisma.StringFilter<"Lease"> | string
}

export type LeaseCreateWithoutTenantInput = {
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  application?: Prisma.ApplicationCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutTenantInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
  application?: Prisma.ApplicationUncheckedCreateNestedOneWithoutLeaseInput
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput>
}

export type LeaseCreateManyTenantInputEnvelope = {
  data: Prisma.LeaseCreateManyTenantInput | Prisma.LeaseCreateManyTenantInput[]
  skipDuplicates?: boolean
}

export type LeaseUpsertWithWhereUniqueWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutTenantInput, Prisma.LeaseUncheckedUpdateWithoutTenantInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutTenantInput, Prisma.LeaseUncheckedCreateWithoutTenantInput>
}

export type LeaseUpdateWithWhereUniqueWithoutTenantInput = {
  where: Prisma.LeaseWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutTenantInput, Prisma.LeaseUncheckedUpdateWithoutTenantInput>
}

export type LeaseUpdateManyWithWhereWithoutTenantInput = {
  where: Prisma.LeaseScalarWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyWithoutTenantInput>
}

export type LeaseCreateWithoutApplicationInput = {
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  tenant: Prisma.TenantCreateNestedOneWithoutLeasesInput
  payments?: Prisma.PaymentCreateNestedManyWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutApplicationInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: string
  payments?: Prisma.PaymentUncheckedCreateNestedManyWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutApplicationInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutApplicationInput, Prisma.LeaseUncheckedCreateWithoutApplicationInput>
}

export type LeaseUpsertWithoutApplicationInput = {
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutApplicationInput, Prisma.LeaseUncheckedUpdateWithoutApplicationInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutApplicationInput, Prisma.LeaseUncheckedCreateWithoutApplicationInput>
  where?: Prisma.LeaseWhereInput
}

export type LeaseUpdateToOneWithWhereWithoutApplicationInput = {
  where?: Prisma.LeaseWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutApplicationInput, Prisma.LeaseUncheckedUpdateWithoutApplicationInput>
}

export type LeaseUpdateWithoutApplicationInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  tenant?: Prisma.TenantUpdateOneRequiredWithoutLeasesNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutApplicationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseCreateWithoutPaymentsInput = {
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  property: Prisma.PropertyCreateNestedOneWithoutLeasesInput
  tenant: Prisma.TenantCreateNestedOneWithoutLeasesInput
  application?: Prisma.ApplicationCreateNestedOneWithoutLeaseInput
}

export type LeaseUncheckedCreateWithoutPaymentsInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
  tenantCognitoId: string
  application?: Prisma.ApplicationUncheckedCreateNestedOneWithoutLeaseInput
}

export type LeaseCreateOrConnectWithoutPaymentsInput = {
  where: Prisma.LeaseWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
}

export type LeaseUpsertWithoutPaymentsInput = {
  update: Prisma.XOR<Prisma.LeaseUpdateWithoutPaymentsInput, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
  create: Prisma.XOR<Prisma.LeaseCreateWithoutPaymentsInput, Prisma.LeaseUncheckedCreateWithoutPaymentsInput>
  where?: Prisma.LeaseWhereInput
}

export type LeaseUpdateToOneWithWhereWithoutPaymentsInput = {
  where?: Prisma.LeaseWhereInput
  data: Prisma.XOR<Prisma.LeaseUpdateWithoutPaymentsInput, Prisma.LeaseUncheckedUpdateWithoutPaymentsInput>
}

export type LeaseUpdateWithoutPaymentsInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  tenant?: Prisma.TenantUpdateOneRequiredWithoutLeasesNestedInput
  application?: Prisma.ApplicationUpdateOneWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutPaymentsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  application?: Prisma.ApplicationUncheckedUpdateOneWithoutLeaseNestedInput
}

export type LeaseCreateManyPropertyInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  tenantCognitoId: string
}

export type LeaseUpdateWithoutPropertyInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  tenant?: Prisma.TenantUpdateOneRequiredWithoutLeasesNestedInput
  application?: Prisma.ApplicationUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutPropertyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  application?: Prisma.ApplicationUncheckedUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateManyWithoutPropertyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  tenantCognitoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type LeaseCreateManyTenantInput = {
  id?: number
  startDate: Date | string
  endDate: Date | string
  rent: number
  deposit: number
  propertyId: number
}

export type LeaseUpdateWithoutTenantInput = {
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  property?: Prisma.PropertyUpdateOneRequiredWithoutLeasesNestedInput
  application?: Prisma.ApplicationUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateWithoutTenantInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
  application?: Prisma.ApplicationUncheckedUpdateOneWithoutLeaseNestedInput
  payments?: Prisma.PaymentUncheckedUpdateManyWithoutLeaseNestedInput
}

export type LeaseUncheckedUpdateManyWithoutTenantInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rent?: Prisma.FloatFieldUpdateOperationsInput | number
  deposit?: Prisma.FloatFieldUpdateOperationsInput | number
  propertyId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type LeaseCountOutputType
 */

export type LeaseCountOutputType = {
  payments: number
}

export type LeaseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  payments?: boolean | LeaseCountOutputTypeCountPaymentsArgs
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaseCountOutputType
   */
  select?: Prisma.LeaseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * LeaseCountOutputType without action
 */
export type LeaseCountOutputTypeCountPaymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentWhereInput
}


export type LeaseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  rent?: boolean
  deposit?: boolean
  propertyId?: boolean
  tenantCognitoId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  application?: boolean | Prisma.Lease$applicationArgs<ExtArgs>
  payments?: boolean | Prisma.Lease$paymentsArgs<ExtArgs>
  _count?: boolean | Prisma.LeaseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  rent?: boolean
  deposit?: boolean
  propertyId?: boolean
  tenantCognitoId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  rent?: boolean
  deposit?: boolean
  propertyId?: boolean
  tenantCognitoId?: boolean
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["lease"]>

export type LeaseSelectScalar = {
  id?: boolean
  startDate?: boolean
  endDate?: boolean
  rent?: boolean
  deposit?: boolean
  propertyId?: boolean
  tenantCognitoId?: boolean
}

export type LeaseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "startDate" | "endDate" | "rent" | "deposit" | "propertyId" | "tenantCognitoId", ExtArgs["result"]["lease"]>
export type LeaseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
  application?: boolean | Prisma.Lease$applicationArgs<ExtArgs>
  payments?: boolean | Prisma.Lease$paymentsArgs<ExtArgs>
  _count?: boolean | Prisma.LeaseCountOutputTypeDefaultArgs<ExtArgs>
}
export type LeaseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
}
export type LeaseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  property?: boolean | Prisma.PropertyDefaultArgs<ExtArgs>
  tenant?: boolean | Prisma.TenantDefaultArgs<ExtArgs>
}

export type $LeasePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Lease"
  objects: {
    property: Prisma.$PropertyPayload<ExtArgs>
    tenant: Prisma.$TenantPayload<ExtArgs>
    application: Prisma.$ApplicationPayload<ExtArgs> | null
    payments: Prisma.$PaymentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    startDate: Date
    endDate: Date
    rent: number
    deposit: number
    propertyId: number
    tenantCognitoId: string
  }, ExtArgs["result"]["lease"]>
  composites: {}
}

export type LeaseGetPayload<S extends boolean | null | undefined | LeaseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeasePayload, S>

export type LeaseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeaseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeaseCountAggregateInputType | true
  }

export interface LeaseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Lease'], meta: { name: 'Lease' } }
  /**
   * Find zero or one Lease that matches the filter.
   * @param {LeaseFindUniqueArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeaseFindUniqueArgs>(args: Prisma.SelectSubset<T, LeaseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Lease that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeaseFindUniqueOrThrowArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeaseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeaseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lease that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindFirstArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeaseFindFirstArgs>(args?: Prisma.SelectSubset<T, LeaseFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Lease that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindFirstOrThrowArgs} args - Arguments to find a Lease
   * @example
   * // Get one Lease
   * const lease = await prisma.lease.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeaseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeaseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Leases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Leases
   * const leases = await prisma.lease.findMany()
   * 
   * // Get first 10 Leases
   * const leases = await prisma.lease.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leaseWithIdOnly = await prisma.lease.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeaseFindManyArgs>(args?: Prisma.SelectSubset<T, LeaseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Lease.
   * @param {LeaseCreateArgs} args - Arguments to create a Lease.
   * @example
   * // Create one Lease
   * const Lease = await prisma.lease.create({
   *   data: {
   *     // ... data to create a Lease
   *   }
   * })
   * 
   */
  create<T extends LeaseCreateArgs>(args: Prisma.SelectSubset<T, LeaseCreateArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Leases.
   * @param {LeaseCreateManyArgs} args - Arguments to create many Leases.
   * @example
   * // Create many Leases
   * const lease = await prisma.lease.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeaseCreateManyArgs>(args?: Prisma.SelectSubset<T, LeaseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Leases and returns the data saved in the database.
   * @param {LeaseCreateManyAndReturnArgs} args - Arguments to create many Leases.
   * @example
   * // Create many Leases
   * const lease = await prisma.lease.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Leases and only return the `id`
   * const leaseWithIdOnly = await prisma.lease.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeaseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeaseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Lease.
   * @param {LeaseDeleteArgs} args - Arguments to delete one Lease.
   * @example
   * // Delete one Lease
   * const Lease = await prisma.lease.delete({
   *   where: {
   *     // ... filter to delete one Lease
   *   }
   * })
   * 
   */
  delete<T extends LeaseDeleteArgs>(args: Prisma.SelectSubset<T, LeaseDeleteArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Lease.
   * @param {LeaseUpdateArgs} args - Arguments to update one Lease.
   * @example
   * // Update one Lease
   * const lease = await prisma.lease.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeaseUpdateArgs>(args: Prisma.SelectSubset<T, LeaseUpdateArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Leases.
   * @param {LeaseDeleteManyArgs} args - Arguments to filter Leases to delete.
   * @example
   * // Delete a few Leases
   * const { count } = await prisma.lease.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeaseDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeaseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Leases
   * const lease = await prisma.lease.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeaseUpdateManyArgs>(args: Prisma.SelectSubset<T, LeaseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Leases and returns the data updated in the database.
   * @param {LeaseUpdateManyAndReturnArgs} args - Arguments to update many Leases.
   * @example
   * // Update many Leases
   * const lease = await prisma.lease.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Leases and only return the `id`
   * const leaseWithIdOnly = await prisma.lease.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeaseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeaseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Lease.
   * @param {LeaseUpsertArgs} args - Arguments to update or create a Lease.
   * @example
   * // Update or create a Lease
   * const lease = await prisma.lease.upsert({
   *   create: {
   *     // ... data to create a Lease
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Lease we want to update
   *   }
   * })
   */
  upsert<T extends LeaseUpsertArgs>(args: Prisma.SelectSubset<T, LeaseUpsertArgs<ExtArgs>>): Prisma.Prisma__LeaseClient<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Leases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseCountArgs} args - Arguments to filter Leases to count.
   * @example
   * // Count the number of Leases
   * const count = await prisma.lease.count({
   *   where: {
   *     // ... the filter for the Leases we want to count
   *   }
   * })
  **/
  count<T extends LeaseCountArgs>(
    args?: Prisma.Subset<T, LeaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Lease.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeaseAggregateArgs>(args: Prisma.Subset<T, LeaseAggregateArgs>): Prisma.PrismaPromise<GetLeaseAggregateType<T>>

  /**
   * Group by Lease.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeaseGroupByArgs['orderBy'] }
      : { orderBy?: LeaseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeaseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Lease model
 */
readonly fields: LeaseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Lease.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeaseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  property<T extends Prisma.PropertyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PropertyDefaultArgs<ExtArgs>>): Prisma.Prisma__PropertyClient<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tenant<T extends Prisma.TenantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TenantDefaultArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  application<T extends Prisma.Lease$applicationArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lease$applicationArgs<ExtArgs>>): Prisma.Prisma__ApplicationClient<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  payments<T extends Prisma.Lease$paymentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Lease$paymentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Lease model
 */
export interface LeaseFieldRefs {
  readonly id: Prisma.FieldRef<"Lease", 'Int'>
  readonly startDate: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"Lease", 'DateTime'>
  readonly rent: Prisma.FieldRef<"Lease", 'Float'>
  readonly deposit: Prisma.FieldRef<"Lease", 'Float'>
  readonly propertyId: Prisma.FieldRef<"Lease", 'Int'>
  readonly tenantCognitoId: Prisma.FieldRef<"Lease", 'String'>
}
    

// Custom InputTypes
/**
 * Lease findUnique
 */
export type LeaseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease findUniqueOrThrow
 */
export type LeaseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease findFirst
 */
export type LeaseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leases.
   */
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease findFirstOrThrow
 */
export type LeaseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Lease to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Leases.
   */
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease findMany
 */
export type LeaseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter, which Leases to fetch.
   */
  where?: Prisma.LeaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Leases to fetch.
   */
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Leases.
   */
  cursor?: Prisma.LeaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Leases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Leases.
   */
  skip?: number
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Lease create
 */
export type LeaseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The data needed to create a Lease.
   */
  data: Prisma.XOR<Prisma.LeaseCreateInput, Prisma.LeaseUncheckedCreateInput>
}

/**
 * Lease createMany
 */
export type LeaseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Leases.
   */
  data: Prisma.LeaseCreateManyInput | Prisma.LeaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Lease createManyAndReturn
 */
export type LeaseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * The data used to create many Leases.
   */
  data: Prisma.LeaseCreateManyInput | Prisma.LeaseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Lease update
 */
export type LeaseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The data needed to update a Lease.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateInput, Prisma.LeaseUncheckedUpdateInput>
  /**
   * Choose, which Lease to update.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease updateMany
 */
export type LeaseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Leases.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyInput>
  /**
   * Filter which Leases to update
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to update.
   */
  limit?: number
}

/**
 * Lease updateManyAndReturn
 */
export type LeaseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * The data used to update Leases.
   */
  data: Prisma.XOR<Prisma.LeaseUpdateManyMutationInput, Prisma.LeaseUncheckedUpdateManyInput>
  /**
   * Filter which Leases to update
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Lease upsert
 */
export type LeaseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * The filter to search for the Lease to update in case it exists.
   */
  where: Prisma.LeaseWhereUniqueInput
  /**
   * In case the Lease found by the `where` argument doesn't exist, create a new Lease with this data.
   */
  create: Prisma.XOR<Prisma.LeaseCreateInput, Prisma.LeaseUncheckedCreateInput>
  /**
   * In case the Lease was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeaseUpdateInput, Prisma.LeaseUncheckedUpdateInput>
}

/**
 * Lease delete
 */
export type LeaseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  /**
   * Filter which Lease to delete.
   */
  where: Prisma.LeaseWhereUniqueInput
}

/**
 * Lease deleteMany
 */
export type LeaseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Leases to delete
   */
  where?: Prisma.LeaseWhereInput
  /**
   * Limit how many Leases to delete.
   */
  limit?: number
}

/**
 * Lease.application
 */
export type Lease$applicationArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationInclude<ExtArgs> | null
  where?: Prisma.ApplicationWhereInput
}

/**
 * Lease.payments
 */
export type Lease$paymentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Payment
   */
  select?: Prisma.PaymentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Payment
   */
  omit?: Prisma.PaymentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentInclude<ExtArgs> | null
  where?: Prisma.PaymentWhereInput
  orderBy?: Prisma.PaymentOrderByWithRelationInput | Prisma.PaymentOrderByWithRelationInput[]
  cursor?: Prisma.PaymentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PaymentScalarFieldEnum | Prisma.PaymentScalarFieldEnum[]
}

/**
 * Lease without action
 */
export type LeaseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
}
