
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Tenant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Tenant
 * 
 */
export type TenantModel = runtime.Types.Result.DefaultSelection<Prisma.$TenantPayload>

export type AggregateTenant = {
  _count: TenantCountAggregateOutputType | null
  _avg: TenantAvgAggregateOutputType | null
  _sum: TenantSumAggregateOutputType | null
  _min: TenantMinAggregateOutputType | null
  _max: TenantMaxAggregateOutputType | null
}

export type TenantAvgAggregateOutputType = {
  id: number | null
}

export type TenantSumAggregateOutputType = {
  id: number | null
}

export type TenantMinAggregateOutputType = {
  id: number | null
  cognitoId: string | null
  name: string | null
  email: string | null
  phoneNumber: string | null
}

export type TenantMaxAggregateOutputType = {
  id: number | null
  cognitoId: string | null
  name: string | null
  email: string | null
  phoneNumber: string | null
}

export type TenantCountAggregateOutputType = {
  id: number
  cognitoId: number
  name: number
  email: number
  phoneNumber: number
  _all: number
}


export type TenantAvgAggregateInputType = {
  id?: true
}

export type TenantSumAggregateInputType = {
  id?: true
}

export type TenantMinAggregateInputType = {
  id?: true
  cognitoId?: true
  name?: true
  email?: true
  phoneNumber?: true
}

export type TenantMaxAggregateInputType = {
  id?: true
  cognitoId?: true
  name?: true
  email?: true
  phoneNumber?: true
}

export type TenantCountAggregateInputType = {
  id?: true
  cognitoId?: true
  name?: true
  email?: true
  phoneNumber?: true
  _all?: true
}

export type TenantAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenant to aggregate.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tenants
  **/
  _count?: true | TenantCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TenantAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TenantSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TenantMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TenantMaxAggregateInputType
}

export type GetTenantAggregateType<T extends TenantAggregateArgs> = {
      [P in keyof T & keyof AggregateTenant]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTenant[P]>
    : Prisma.GetScalarType<T[P], AggregateTenant[P]>
}




export type TenantGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TenantWhereInput
  orderBy?: Prisma.TenantOrderByWithAggregationInput | Prisma.TenantOrderByWithAggregationInput[]
  by: Prisma.TenantScalarFieldEnum[] | Prisma.TenantScalarFieldEnum
  having?: Prisma.TenantScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TenantCountAggregateInputType | true
  _avg?: TenantAvgAggregateInputType
  _sum?: TenantSumAggregateInputType
  _min?: TenantMinAggregateInputType
  _max?: TenantMaxAggregateInputType
}

export type TenantGroupByOutputType = {
  id: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  _count: TenantCountAggregateOutputType | null
  _avg: TenantAvgAggregateOutputType | null
  _sum: TenantSumAggregateOutputType | null
  _min: TenantMinAggregateOutputType | null
  _max: TenantMaxAggregateOutputType | null
}

type GetTenantGroupByPayload<T extends TenantGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TenantGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TenantGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TenantGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TenantGroupByOutputType[P]>
      }
    >
  >



export type TenantWhereInput = {
  AND?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  OR?: Prisma.TenantWhereInput[]
  NOT?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  id?: Prisma.IntFilter<"Tenant"> | number
  cognitoId?: Prisma.StringFilter<"Tenant"> | string
  name?: Prisma.StringFilter<"Tenant"> | string
  email?: Prisma.StringFilter<"Tenant"> | string
  phoneNumber?: Prisma.StringFilter<"Tenant"> | string
  properties?: Prisma.PropertyListRelationFilter
  favorites?: Prisma.PropertyListRelationFilter
  applications?: Prisma.ApplicationListRelationFilter
  leases?: Prisma.LeaseListRelationFilter
}

export type TenantOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cognitoId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  properties?: Prisma.PropertyOrderByRelationAggregateInput
  favorites?: Prisma.PropertyOrderByRelationAggregateInput
  applications?: Prisma.ApplicationOrderByRelationAggregateInput
  leases?: Prisma.LeaseOrderByRelationAggregateInput
}

export type TenantWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  cognitoId?: string
  AND?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  OR?: Prisma.TenantWhereInput[]
  NOT?: Prisma.TenantWhereInput | Prisma.TenantWhereInput[]
  name?: Prisma.StringFilter<"Tenant"> | string
  email?: Prisma.StringFilter<"Tenant"> | string
  phoneNumber?: Prisma.StringFilter<"Tenant"> | string
  properties?: Prisma.PropertyListRelationFilter
  favorites?: Prisma.PropertyListRelationFilter
  applications?: Prisma.ApplicationListRelationFilter
  leases?: Prisma.LeaseListRelationFilter
}, "id" | "cognitoId">

export type TenantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cognitoId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
  _count?: Prisma.TenantCountOrderByAggregateInput
  _avg?: Prisma.TenantAvgOrderByAggregateInput
  _max?: Prisma.TenantMaxOrderByAggregateInput
  _min?: Prisma.TenantMinOrderByAggregateInput
  _sum?: Prisma.TenantSumOrderByAggregateInput
}

export type TenantScalarWhereWithAggregatesInput = {
  AND?: Prisma.TenantScalarWhereWithAggregatesInput | Prisma.TenantScalarWhereWithAggregatesInput[]
  OR?: Prisma.TenantScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TenantScalarWhereWithAggregatesInput | Prisma.TenantScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Tenant"> | number
  cognitoId?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  name?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  email?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
  phoneNumber?: Prisma.StringWithAggregatesFilter<"Tenant"> | string
}

export type TenantCreateInput = {
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyUncheckedCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyUncheckedCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantUpdateInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUncheckedUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUncheckedUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateManyInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
}

export type TenantUpdateManyMutationInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TenantUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TenantListRelationFilter = {
  every?: Prisma.TenantWhereInput
  some?: Prisma.TenantWhereInput
  none?: Prisma.TenantWhereInput
}

export type TenantOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TenantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cognitoId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
}

export type TenantAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TenantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cognitoId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
}

export type TenantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cognitoId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phoneNumber?: Prisma.SortOrder
}

export type TenantSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TenantScalarRelationFilter = {
  is?: Prisma.TenantWhereInput
  isNot?: Prisma.TenantWhereInput
}

export type TenantCreateNestedManyWithoutFavoritesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput> | Prisma.TenantCreateWithoutFavoritesInput[] | Prisma.TenantUncheckedCreateWithoutFavoritesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutFavoritesInput | Prisma.TenantCreateOrConnectWithoutFavoritesInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
}

export type TenantCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput> | Prisma.TenantCreateWithoutPropertiesInput[] | Prisma.TenantUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutPropertiesInput | Prisma.TenantCreateOrConnectWithoutPropertiesInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
}

export type TenantUncheckedCreateNestedManyWithoutFavoritesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput> | Prisma.TenantCreateWithoutFavoritesInput[] | Prisma.TenantUncheckedCreateWithoutFavoritesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutFavoritesInput | Prisma.TenantCreateOrConnectWithoutFavoritesInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
}

export type TenantUncheckedCreateNestedManyWithoutPropertiesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput> | Prisma.TenantCreateWithoutPropertiesInput[] | Prisma.TenantUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutPropertiesInput | Prisma.TenantCreateOrConnectWithoutPropertiesInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
}

export type TenantUpdateManyWithoutFavoritesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput> | Prisma.TenantCreateWithoutFavoritesInput[] | Prisma.TenantUncheckedCreateWithoutFavoritesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutFavoritesInput | Prisma.TenantCreateOrConnectWithoutFavoritesInput[]
  upsert?: Prisma.TenantUpsertWithWhereUniqueWithoutFavoritesInput | Prisma.TenantUpsertWithWhereUniqueWithoutFavoritesInput[]
  set?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  disconnect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  delete?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  update?: Prisma.TenantUpdateWithWhereUniqueWithoutFavoritesInput | Prisma.TenantUpdateWithWhereUniqueWithoutFavoritesInput[]
  updateMany?: Prisma.TenantUpdateManyWithWhereWithoutFavoritesInput | Prisma.TenantUpdateManyWithWhereWithoutFavoritesInput[]
  deleteMany?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
}

export type TenantUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput> | Prisma.TenantCreateWithoutPropertiesInput[] | Prisma.TenantUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutPropertiesInput | Prisma.TenantCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.TenantUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.TenantUpsertWithWhereUniqueWithoutPropertiesInput[]
  set?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  disconnect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  delete?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  update?: Prisma.TenantUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.TenantUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.TenantUpdateManyWithWhereWithoutPropertiesInput | Prisma.TenantUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
}

export type TenantUncheckedUpdateManyWithoutFavoritesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput> | Prisma.TenantCreateWithoutFavoritesInput[] | Prisma.TenantUncheckedCreateWithoutFavoritesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutFavoritesInput | Prisma.TenantCreateOrConnectWithoutFavoritesInput[]
  upsert?: Prisma.TenantUpsertWithWhereUniqueWithoutFavoritesInput | Prisma.TenantUpsertWithWhereUniqueWithoutFavoritesInput[]
  set?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  disconnect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  delete?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  update?: Prisma.TenantUpdateWithWhereUniqueWithoutFavoritesInput | Prisma.TenantUpdateWithWhereUniqueWithoutFavoritesInput[]
  updateMany?: Prisma.TenantUpdateManyWithWhereWithoutFavoritesInput | Prisma.TenantUpdateManyWithWhereWithoutFavoritesInput[]
  deleteMany?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
}

export type TenantUncheckedUpdateManyWithoutPropertiesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput> | Prisma.TenantCreateWithoutPropertiesInput[] | Prisma.TenantUncheckedCreateWithoutPropertiesInput[]
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutPropertiesInput | Prisma.TenantCreateOrConnectWithoutPropertiesInput[]
  upsert?: Prisma.TenantUpsertWithWhereUniqueWithoutPropertiesInput | Prisma.TenantUpsertWithWhereUniqueWithoutPropertiesInput[]
  set?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  disconnect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  delete?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  connect?: Prisma.TenantWhereUniqueInput | Prisma.TenantWhereUniqueInput[]
  update?: Prisma.TenantUpdateWithWhereUniqueWithoutPropertiesInput | Prisma.TenantUpdateWithWhereUniqueWithoutPropertiesInput[]
  updateMany?: Prisma.TenantUpdateManyWithWhereWithoutPropertiesInput | Prisma.TenantUpdateManyWithWhereWithoutPropertiesInput[]
  deleteMany?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
}

export type TenantCreateNestedOneWithoutApplicationsInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutApplicationsInput, Prisma.TenantUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutApplicationsInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutApplicationsNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutApplicationsInput, Prisma.TenantUncheckedCreateWithoutApplicationsInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutApplicationsInput
  upsert?: Prisma.TenantUpsertWithoutApplicationsInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutApplicationsInput, Prisma.TenantUpdateWithoutApplicationsInput>, Prisma.TenantUncheckedUpdateWithoutApplicationsInput>
}

export type TenantCreateNestedOneWithoutLeasesInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutLeasesInput, Prisma.TenantUncheckedCreateWithoutLeasesInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutLeasesInput
  connect?: Prisma.TenantWhereUniqueInput
}

export type TenantUpdateOneRequiredWithoutLeasesNestedInput = {
  create?: Prisma.XOR<Prisma.TenantCreateWithoutLeasesInput, Prisma.TenantUncheckedCreateWithoutLeasesInput>
  connectOrCreate?: Prisma.TenantCreateOrConnectWithoutLeasesInput
  upsert?: Prisma.TenantUpsertWithoutLeasesInput
  connect?: Prisma.TenantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TenantUpdateToOneWithWhereWithoutLeasesInput, Prisma.TenantUpdateWithoutLeasesInput>, Prisma.TenantUncheckedUpdateWithoutLeasesInput>
}

export type TenantCreateWithoutFavoritesInput = {
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyCreateNestedManyWithoutTenantsInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutFavoritesInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyUncheckedCreateNestedManyWithoutTenantsInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutFavoritesInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput>
}

export type TenantCreateWithoutPropertiesInput = {
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  favorites?: Prisma.PropertyCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutPropertiesInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  favorites?: Prisma.PropertyUncheckedCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutTenantInput
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutPropertiesInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput>
}

export type TenantUpsertWithWhereUniqueWithoutFavoritesInput = {
  where: Prisma.TenantWhereUniqueInput
  update: Prisma.XOR<Prisma.TenantUpdateWithoutFavoritesInput, Prisma.TenantUncheckedUpdateWithoutFavoritesInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutFavoritesInput, Prisma.TenantUncheckedCreateWithoutFavoritesInput>
}

export type TenantUpdateWithWhereUniqueWithoutFavoritesInput = {
  where: Prisma.TenantWhereUniqueInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutFavoritesInput, Prisma.TenantUncheckedUpdateWithoutFavoritesInput>
}

export type TenantUpdateManyWithWhereWithoutFavoritesInput = {
  where: Prisma.TenantScalarWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyWithoutFavoritesInput>
}

export type TenantScalarWhereInput = {
  AND?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
  OR?: Prisma.TenantScalarWhereInput[]
  NOT?: Prisma.TenantScalarWhereInput | Prisma.TenantScalarWhereInput[]
  id?: Prisma.IntFilter<"Tenant"> | number
  cognitoId?: Prisma.StringFilter<"Tenant"> | string
  name?: Prisma.StringFilter<"Tenant"> | string
  email?: Prisma.StringFilter<"Tenant"> | string
  phoneNumber?: Prisma.StringFilter<"Tenant"> | string
}

export type TenantUpsertWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.TenantWhereUniqueInput
  update: Prisma.XOR<Prisma.TenantUpdateWithoutPropertiesInput, Prisma.TenantUncheckedUpdateWithoutPropertiesInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutPropertiesInput, Prisma.TenantUncheckedCreateWithoutPropertiesInput>
}

export type TenantUpdateWithWhereUniqueWithoutPropertiesInput = {
  where: Prisma.TenantWhereUniqueInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutPropertiesInput, Prisma.TenantUncheckedUpdateWithoutPropertiesInput>
}

export type TenantUpdateManyWithWhereWithoutPropertiesInput = {
  where: Prisma.TenantScalarWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyWithoutPropertiesInput>
}

export type TenantCreateWithoutApplicationsInput = {
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyCreateNestedManyWithoutFavoritedByInput
  leases?: Prisma.LeaseCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutApplicationsInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyUncheckedCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyUncheckedCreateNestedManyWithoutFavoritedByInput
  leases?: Prisma.LeaseUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutApplicationsInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutApplicationsInput, Prisma.TenantUncheckedCreateWithoutApplicationsInput>
}

export type TenantUpsertWithoutApplicationsInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutApplicationsInput, Prisma.TenantUncheckedUpdateWithoutApplicationsInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutApplicationsInput, Prisma.TenantUncheckedCreateWithoutApplicationsInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutApplicationsInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutApplicationsInput, Prisma.TenantUncheckedUpdateWithoutApplicationsInput>
}

export type TenantUpdateWithoutApplicationsInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUpdateManyWithoutFavoritedByNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutApplicationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUncheckedUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUncheckedUpdateManyWithoutFavoritedByNestedInput
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantCreateWithoutLeasesInput = {
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationCreateNestedManyWithoutTenantInput
}

export type TenantUncheckedCreateWithoutLeasesInput = {
  id?: number
  cognitoId: string
  name: string
  email: string
  phoneNumber: string
  properties?: Prisma.PropertyUncheckedCreateNestedManyWithoutTenantsInput
  favorites?: Prisma.PropertyUncheckedCreateNestedManyWithoutFavoritedByInput
  applications?: Prisma.ApplicationUncheckedCreateNestedManyWithoutTenantInput
}

export type TenantCreateOrConnectWithoutLeasesInput = {
  where: Prisma.TenantWhereUniqueInput
  create: Prisma.XOR<Prisma.TenantCreateWithoutLeasesInput, Prisma.TenantUncheckedCreateWithoutLeasesInput>
}

export type TenantUpsertWithoutLeasesInput = {
  update: Prisma.XOR<Prisma.TenantUpdateWithoutLeasesInput, Prisma.TenantUncheckedUpdateWithoutLeasesInput>
  create: Prisma.XOR<Prisma.TenantCreateWithoutLeasesInput, Prisma.TenantUncheckedCreateWithoutLeasesInput>
  where?: Prisma.TenantWhereInput
}

export type TenantUpdateToOneWithWhereWithoutLeasesInput = {
  where?: Prisma.TenantWhereInput
  data: Prisma.XOR<Prisma.TenantUpdateWithoutLeasesInput, Prisma.TenantUncheckedUpdateWithoutLeasesInput>
}

export type TenantUpdateWithoutLeasesInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutLeasesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUncheckedUpdateManyWithoutTenantsNestedInput
  favorites?: Prisma.PropertyUncheckedUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantUpdateWithoutFavoritesInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUpdateManyWithoutTenantsNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutFavoritesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  properties?: Prisma.PropertyUncheckedUpdateManyWithoutTenantsNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateManyWithoutFavoritesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TenantUpdateWithoutPropertiesInput = {
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  favorites?: Prisma.PropertyUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateWithoutPropertiesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
  favorites?: Prisma.PropertyUncheckedUpdateManyWithoutFavoritedByNestedInput
  applications?: Prisma.ApplicationUncheckedUpdateManyWithoutTenantNestedInput
  leases?: Prisma.LeaseUncheckedUpdateManyWithoutTenantNestedInput
}

export type TenantUncheckedUpdateManyWithoutPropertiesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cognitoId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phoneNumber?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TenantCountOutputType
 */

export type TenantCountOutputType = {
  properties: number
  favorites: number
  applications: number
  leases: number
}

export type TenantCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | TenantCountOutputTypeCountPropertiesArgs
  favorites?: boolean | TenantCountOutputTypeCountFavoritesArgs
  applications?: boolean | TenantCountOutputTypeCountApplicationsArgs
  leases?: boolean | TenantCountOutputTypeCountLeasesArgs
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TenantCountOutputType
   */
  select?: Prisma.TenantCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountPropertiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountFavoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PropertyWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountApplicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationWhereInput
}

/**
 * TenantCountOutputType without action
 */
export type TenantCountOutputTypeCountLeasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaseWhereInput
}


export type TenantSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cognitoId?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
  properties?: boolean | Prisma.Tenant$propertiesArgs<ExtArgs>
  favorites?: boolean | Prisma.Tenant$favoritesArgs<ExtArgs>
  applications?: boolean | Prisma.Tenant$applicationsArgs<ExtArgs>
  leases?: boolean | Prisma.Tenant$leasesArgs<ExtArgs>
  _count?: boolean | Prisma.TenantCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tenant"]>

export type TenantSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cognitoId?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
}, ExtArgs["result"]["tenant"]>

export type TenantSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  cognitoId?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
}, ExtArgs["result"]["tenant"]>

export type TenantSelectScalar = {
  id?: boolean
  cognitoId?: boolean
  name?: boolean
  email?: boolean
  phoneNumber?: boolean
}

export type TenantOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "cognitoId" | "name" | "email" | "phoneNumber", ExtArgs["result"]["tenant"]>
export type TenantInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  properties?: boolean | Prisma.Tenant$propertiesArgs<ExtArgs>
  favorites?: boolean | Prisma.Tenant$favoritesArgs<ExtArgs>
  applications?: boolean | Prisma.Tenant$applicationsArgs<ExtArgs>
  leases?: boolean | Prisma.Tenant$leasesArgs<ExtArgs>
  _count?: boolean | Prisma.TenantCountOutputTypeDefaultArgs<ExtArgs>
}
export type TenantIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TenantIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TenantPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Tenant"
  objects: {
    properties: Prisma.$PropertyPayload<ExtArgs>[]
    favorites: Prisma.$PropertyPayload<ExtArgs>[]
    applications: Prisma.$ApplicationPayload<ExtArgs>[]
    leases: Prisma.$LeasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    cognitoId: string
    name: string
    email: string
    phoneNumber: string
  }, ExtArgs["result"]["tenant"]>
  composites: {}
}

export type TenantGetPayload<S extends boolean | null | undefined | TenantDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TenantPayload, S>

export type TenantCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TenantFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TenantCountAggregateInputType | true
  }

export interface TenantDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Tenant'], meta: { name: 'Tenant' } }
  /**
   * Find zero or one Tenant that matches the filter.
   * @param {TenantFindUniqueArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TenantFindUniqueArgs>(args: Prisma.SelectSubset<T, TenantFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Tenant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TenantFindUniqueOrThrowArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TenantFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TenantFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindFirstArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TenantFindFirstArgs>(args?: Prisma.SelectSubset<T, TenantFindFirstArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Tenant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindFirstOrThrowArgs} args - Arguments to find a Tenant
   * @example
   * // Get one Tenant
   * const tenant = await prisma.tenant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TenantFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TenantFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tenants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tenants
   * const tenants = await prisma.tenant.findMany()
   * 
   * // Get first 10 Tenants
   * const tenants = await prisma.tenant.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tenantWithIdOnly = await prisma.tenant.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TenantFindManyArgs>(args?: Prisma.SelectSubset<T, TenantFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Tenant.
   * @param {TenantCreateArgs} args - Arguments to create a Tenant.
   * @example
   * // Create one Tenant
   * const Tenant = await prisma.tenant.create({
   *   data: {
   *     // ... data to create a Tenant
   *   }
   * })
   * 
   */
  create<T extends TenantCreateArgs>(args: Prisma.SelectSubset<T, TenantCreateArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tenants.
   * @param {TenantCreateManyArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenant = await prisma.tenant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TenantCreateManyArgs>(args?: Prisma.SelectSubset<T, TenantCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tenants and returns the data saved in the database.
   * @param {TenantCreateManyAndReturnArgs} args - Arguments to create many Tenants.
   * @example
   * // Create many Tenants
   * const tenant = await prisma.tenant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tenants and only return the `id`
   * const tenantWithIdOnly = await prisma.tenant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TenantCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TenantCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Tenant.
   * @param {TenantDeleteArgs} args - Arguments to delete one Tenant.
   * @example
   * // Delete one Tenant
   * const Tenant = await prisma.tenant.delete({
   *   where: {
   *     // ... filter to delete one Tenant
   *   }
   * })
   * 
   */
  delete<T extends TenantDeleteArgs>(args: Prisma.SelectSubset<T, TenantDeleteArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Tenant.
   * @param {TenantUpdateArgs} args - Arguments to update one Tenant.
   * @example
   * // Update one Tenant
   * const tenant = await prisma.tenant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TenantUpdateArgs>(args: Prisma.SelectSubset<T, TenantUpdateArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tenants.
   * @param {TenantDeleteManyArgs} args - Arguments to filter Tenants to delete.
   * @example
   * // Delete a few Tenants
   * const { count } = await prisma.tenant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TenantDeleteManyArgs>(args?: Prisma.SelectSubset<T, TenantDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tenants
   * const tenant = await prisma.tenant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TenantUpdateManyArgs>(args: Prisma.SelectSubset<T, TenantUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tenants and returns the data updated in the database.
   * @param {TenantUpdateManyAndReturnArgs} args - Arguments to update many Tenants.
   * @example
   * // Update many Tenants
   * const tenant = await prisma.tenant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tenants and only return the `id`
   * const tenantWithIdOnly = await prisma.tenant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TenantUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TenantUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Tenant.
   * @param {TenantUpsertArgs} args - Arguments to update or create a Tenant.
   * @example
   * // Update or create a Tenant
   * const tenant = await prisma.tenant.upsert({
   *   create: {
   *     // ... data to create a Tenant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Tenant we want to update
   *   }
   * })
   */
  upsert<T extends TenantUpsertArgs>(args: Prisma.SelectSubset<T, TenantUpsertArgs<ExtArgs>>): Prisma.Prisma__TenantClient<runtime.Types.Result.GetResult<Prisma.$TenantPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tenants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantCountArgs} args - Arguments to filter Tenants to count.
   * @example
   * // Count the number of Tenants
   * const count = await prisma.tenant.count({
   *   where: {
   *     // ... the filter for the Tenants we want to count
   *   }
   * })
  **/
  count<T extends TenantCountArgs>(
    args?: Prisma.Subset<T, TenantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TenantCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Tenant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TenantAggregateArgs>(args: Prisma.Subset<T, TenantAggregateArgs>): Prisma.PrismaPromise<GetTenantAggregateType<T>>

  /**
   * Group by Tenant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TenantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TenantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TenantGroupByArgs['orderBy'] }
      : { orderBy?: TenantGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TenantGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTenantGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Tenant model
 */
readonly fields: TenantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Tenant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TenantClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  properties<T extends Prisma.Tenant$propertiesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$propertiesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  favorites<T extends Prisma.Tenant$favoritesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$favoritesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PropertyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  applications<T extends Prisma.Tenant$applicationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$applicationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  leases<T extends Prisma.Tenant$leasesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Tenant$leasesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Tenant model
 */
export interface TenantFieldRefs {
  readonly id: Prisma.FieldRef<"Tenant", 'Int'>
  readonly cognitoId: Prisma.FieldRef<"Tenant", 'String'>
  readonly name: Prisma.FieldRef<"Tenant", 'String'>
  readonly email: Prisma.FieldRef<"Tenant", 'String'>
  readonly phoneNumber: Prisma.FieldRef<"Tenant", 'String'>
}
    

// Custom InputTypes
/**
 * Tenant findUnique
 */
export type TenantFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant findUniqueOrThrow
 */
export type TenantFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant findFirst
 */
export type TenantFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant findFirstOrThrow
 */
export type TenantFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenant to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tenants.
   */
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant findMany
 */
export type TenantFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter, which Tenants to fetch.
   */
  where?: Prisma.TenantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tenants to fetch.
   */
  orderBy?: Prisma.TenantOrderByWithRelationInput | Prisma.TenantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tenants.
   */
  cursor?: Prisma.TenantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tenants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tenants.
   */
  skip?: number
  distinct?: Prisma.TenantScalarFieldEnum | Prisma.TenantScalarFieldEnum[]
}

/**
 * Tenant create
 */
export type TenantCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The data needed to create a Tenant.
   */
  data: Prisma.XOR<Prisma.TenantCreateInput, Prisma.TenantUncheckedCreateInput>
}

/**
 * Tenant createMany
 */
export type TenantCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantCreateManyInput | Prisma.TenantCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tenant createManyAndReturn
 */
export type TenantCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * The data used to create many Tenants.
   */
  data: Prisma.TenantCreateManyInput | Prisma.TenantCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Tenant update
 */
export type TenantUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The data needed to update a Tenant.
   */
  data: Prisma.XOR<Prisma.TenantUpdateInput, Prisma.TenantUncheckedUpdateInput>
  /**
   * Choose, which Tenant to update.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant updateMany
 */
export type TenantUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
}

/**
 * Tenant updateManyAndReturn
 */
export type TenantUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * The data used to update Tenants.
   */
  data: Prisma.XOR<Prisma.TenantUpdateManyMutationInput, Prisma.TenantUncheckedUpdateManyInput>
  /**
   * Filter which Tenants to update
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to update.
   */
  limit?: number
}

/**
 * Tenant upsert
 */
export type TenantUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * The filter to search for the Tenant to update in case it exists.
   */
  where: Prisma.TenantWhereUniqueInput
  /**
   * In case the Tenant found by the `where` argument doesn't exist, create a new Tenant with this data.
   */
  create: Prisma.XOR<Prisma.TenantCreateInput, Prisma.TenantUncheckedCreateInput>
  /**
   * In case the Tenant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TenantUpdateInput, Prisma.TenantUncheckedUpdateInput>
}

/**
 * Tenant delete
 */
export type TenantDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
  /**
   * Filter which Tenant to delete.
   */
  where: Prisma.TenantWhereUniqueInput
}

/**
 * Tenant deleteMany
 */
export type TenantDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tenants to delete
   */
  where?: Prisma.TenantWhereInput
  /**
   * Limit how many Tenants to delete.
   */
  limit?: number
}

/**
 * Tenant.properties
 */
export type Tenant$propertiesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  cursor?: Prisma.PropertyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Tenant.favorites
 */
export type Tenant$favoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Property
   */
  select?: Prisma.PropertySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Property
   */
  omit?: Prisma.PropertyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PropertyInclude<ExtArgs> | null
  where?: Prisma.PropertyWhereInput
  orderBy?: Prisma.PropertyOrderByWithRelationInput | Prisma.PropertyOrderByWithRelationInput[]
  cursor?: Prisma.PropertyWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PropertyScalarFieldEnum | Prisma.PropertyScalarFieldEnum[]
}

/**
 * Tenant.applications
 */
export type Tenant$applicationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Application
   */
  select?: Prisma.ApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Application
   */
  omit?: Prisma.ApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationInclude<ExtArgs> | null
  where?: Prisma.ApplicationWhereInput
  orderBy?: Prisma.ApplicationOrderByWithRelationInput | Prisma.ApplicationOrderByWithRelationInput[]
  cursor?: Prisma.ApplicationWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApplicationScalarFieldEnum | Prisma.ApplicationScalarFieldEnum[]
}

/**
 * Tenant.leases
 */
export type Tenant$leasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Lease
   */
  select?: Prisma.LeaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Lease
   */
  omit?: Prisma.LeaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaseInclude<ExtArgs> | null
  where?: Prisma.LeaseWhereInput
  orderBy?: Prisma.LeaseOrderByWithRelationInput | Prisma.LeaseOrderByWithRelationInput[]
  cursor?: Prisma.LeaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LeaseScalarFieldEnum | Prisma.LeaseScalarFieldEnum[]
}

/**
 * Tenant without action
 */
export type TenantDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Tenant
   */
  select?: Prisma.TenantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Tenant
   */
  omit?: Prisma.TenantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TenantInclude<ExtArgs> | null
}
