
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Property.js'
export type * from './models/Manager.js'
export type * from './models/Tenant.js'
export type * from './models/Location.js'
export type * from './models/Application.js'
export type * from './models/Lease.js'
export type * from './models/Payment.js'
export type * from './commonInputTypes.js'